package com.elective.school_management_system;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

public class ClientRoomsListActivity extends AppCompatActivity {

    // 1. Declare UI Components (matching IDs from db_client_rooms_list.xml)
    private ImageView btnBack;
    private LinearLayout tabList, searchContainer;
    private TextView tabMap;

    // For demonstration, using placeholder LinearLayouts for the list items
    private LinearLayout item1, item2, item3;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.db_client_rooms_list);

        // 2. Initialize Views
        initViews();

        // 3. Set up Click Listeners
        setupListeners();
    }

    private void initViews() {
        btnBack = findViewById(R.id.btnBack);

        // Toggle tabs
        tabList = findViewById(R.id.tabList);
        tabMap = findViewById(R.id.tabMap);

        // Search bar (container is clickable to initiate search function)
        searchContainer = findViewById(R.id.searchContainer);

        // Note: In a real app, the list items would be generated by a RecyclerView/Adapter.
        // We initialize the mock items for now to show interaction.
        // Assuming the first three items are within an outer LinearLayout in the ScrollView,
        // we'll locate them by their parent index or unique ID if they had one.
        // Since the XML does not provide IDs for the inner list items,
        // you would typically wrap each item in a clickable view (e.g., CardView or LinearLayout) and give it an ID.
        // For now, let's assume you'll add IDs or use an adapter for the list.

        // If you were to add IDs (e.g., R.id.roomItem1), this is how you'd initialize them:
        // item1 = findViewById(R.id.roomItem1);
        // ... and so on.
    }

    private void setupListeners() {
        // --- Back Button Functionality ---
        btnBack.setOnClickListener(v -> finish());

        // --- Tab Logic ---
        // Note: The 'List' tab is visually active in the XML (btn_gradient)
        tabMap.setOnClickListener(v -> {
            Toast.makeText(this, "Navigate to Map View", Toast.LENGTH_SHORT).show();
            // TODO: Navigate to Room Map Activity (db_client_room_map.xml)
        });

        // Clicks on the active tab should do nothing or confirm it's the current view.
        tabList.setOnClickListener(v -> {
            Toast.makeText(this, "Currently viewing List", Toast.LENGTH_SHORT).show();
        });

        // --- Search Functionality ---
        searchContainer.setOnClickListener(v -> {
            // In a real scenario, this would likely open a dedicated search view or enable keyboard input on the EditText
            Toast.makeText(this, "Search initiated...", Toast.LENGTH_SHORT).show();
        });

        // --- List Item Clicks ---
        // You would add listeners here for each room item to navigate to its details.
        // Example: item1.setOnClickListener(v -> navigateToRoomDetails("Room 102"));
    }

    // You would use this method when a list item is clicked
    private void navigateToRoomDetails(String roomName) {
        Intent intent = new Intent(ClientRoomsListActivity.this, RoomDetailsActivity.class);
        intent.putExtra("ROOM_NAME", roomName); // Pass data if needed
        startActivity(intent);
    }


}